# -*- coding: utf-8 -*-
"""Command.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17UYlTcFO3cKwtJ_5fvkUqjHywB5Rr77-
"""

import speech_recognition as sr
import pyautogui
import time
import subprocess


def delete_calculator():
    pyautogui.hotkey('win', 'i')
    time.sleep(2)
    pyautogui.hotkey('tab')
    time.sleep(1)
    pyautogui.press('enter')
    time.sleep(2)
    pyautogui.hotkey('ctrl', 'f')
    time.sleep(1)
    pyautogui.write('Калькулятор')
    time.sleep(1)
    pyautogui.press('enter')
    time.sleep(1)
    pyautogui.hotkey('tab')
    time.sleep(1)
    pyautogui.press('enter')
    time.sleep(1)
    pyautogui.press('enter')
    time.sleep(1)


def open_telegram_and_chat_with_denis():
    subprocess.Popen(r'C:\Path\To\Telegram.exe')
    time.sleep(5)
    pyautogui.hotkey('ctrl', 'f')
    time.sleep(1)
    pyautogui.write('Denis')
    time.sleep(1)
    pyautogui.press('enter')
    time.sleep(1)


def close_all_tabs_and_update_system():
    pyautogui.hotkey('ctrl', 'shift', 'w')
    time.sleep(2)
    pyautogui.hotkey('win', 'i')
    time.sleep(2)
    pyautogui.hotkey('tab')
    time.sleep(1)
    pyautogui.press('enter')
    time.sleep(2)
    pyautogui.hotkey('tab')
    time.sleep(1)
    pyautogui.press('enter')
    time.sleep(2)
    pyautogui.hotkey('tab')
    time.sleep(1)
    pyautogui.press('enter')
    time.sleep(1)

def execute_command(command):
    if "удалить калькулятор" in command:
        delete_calculator()
    elif "открыть телеграм" in command and "денис" in command:
        open_telegram_and_chat_with_denis()
    elif "закрыть все вкладки" in command and "обновить систему" in command:
        close_all_tabs_and_update_system()
    else:
        print("Команда не распознана")